import React, { useState, useRef } from 'react';
import { QRCodeCanvas } from 'qrcode.react';
import './App.css';

function App() {
  const [inputValue, setInputValue] = useState('');
  const [qrValue, setQrValue] = useState('');
  const [qrSize, setQrSize] = useState(128); // Default size
  const [qrColor, setQrColor] = useState('#000000'); // Default color
  const qrRef = useRef();

  const handleInputChange = (e) => {
    setInputValue(e.target.value);
  };

  const handleSizeChange = (e) => {
    setQrSize(e.target.value);
  };

  const handleColorChange = (e) => {
    setQrColor(e.target.value);
  };

  const generateQRCode = () => {
    setQrValue(inputValue);
  };

  const downloadQRCode = () => {
    const canvas = qrRef.current.querySelector('canvas');
    const url = canvas.toDataURL('image/png');
    const a = document.createElement('a');
    
    // Remove http:// or https:// from the beginning
    let filename = inputValue.replace(/^https?:\/\//, '');
    
    // Replace non-alphanumeric characters with underscores and limit length
    filename = filename.replace(/[^a-z0-9]/gi, '_').toLowerCase().slice(0, 20);
    
    // Default to 'qrcode' if filename is empty
    if (!filename) {
      filename = 'qrcode';
    }
    
    a.href = url;
    a.download = `${filename}.png`;
    a.click();
  };

  const getComplementaryColor = (color) => {
    const r = 255 - parseInt(color.slice(1, 3), 16);
    const g = 255 - parseInt(color.slice(3, 5), 16);
    const b = 255 - parseInt(color.slice(5, 7), 16);
    return `rgb(${r}, ${g}, ${b})`;
  };

  return (
    <div className="App">
      <h1>QR Code Generator</h1>
      <p className="expl-message">If you think you know what this does, you got it!</p>
      <label>
        Text to encode:
        <input
          type="text"
          value={inputValue}
          onChange={handleInputChange}
          placeholder="Enter text to encode (usually a URL)"
        />
      </label>
      <label>
        Size:
        <input
          type="number"
          value={qrSize}
          onChange={handleSizeChange}
          placeholder="Size of the QR Code"
          min="64"
          max="512"
        />
      </label>
      <label>
        Colour:
        <input
          type="color"
          value={qrColor}
          onChange={handleColorChange}
        />
      </label>
      <div className="button-group">
        <button onClick={generateQRCode}>Create QR Code</button>
        {qrValue && <button onClick={downloadQRCode}>Download QR Code</button>}
      </div>
      {qrValue && (
        <div className="qr-container" ref={qrRef}>
          <QRCodeCanvas
            value={qrValue}
            size={parseInt(qrSize, 10)}
            fgColor={qrColor}
          />
          <div
            className="qr-overlay"
            style={{ border: `2px solid ${qrColor}` }}
          >
            BMI
          </div>
        </div>
      )}
      {qrValue && (
        <>
          <p className="footer-text">Create your own at qrcode.buckmaster.ca</p>
          <p className="encoded-text">Encoded Text: {qrValue}</p>
        </>
      )}
      <div className="disclaimer">
        <p>This service is totally free; the QR code has no expiry. We are The Buckmaster Institute, Inc., developing web apps at <a href="https://buckmaster.ca" target="_blank" rel="noopener noreferrer">buckmaster.ca</a>.</p>
        <p>Legal Disclaimer: The Buckmaster Institute, Inc. is not responsible for any misuse of the QR codes generated by this service. Use at your own risk.</p>
      </div>
    </div>
  );
}

export default App;
