import React, { useState, useRef } from 'react';
import { QRCodeCanvas } from 'qrcode.react';
import { SketchPicker } from 'react-color';
import './App.css';

function App() {
  const [inputValue, setInputValue] = useState('');
  const [qrValue, setQrValue] = useState('');
  const [qrSize, setQrSize] = useState(128); // Default size
  const [qrColor, setQrColor] = useState('#8a1a1e'); // Default color
  const [showColorPicker, setShowColorPicker] = useState(false); // State for color picker visibility
  const qrRef = useRef();

  const handleInputChange = (e) => {
    setInputValue(e.target.value);
  };

  const handleSizeChange = (e) => {
    setQrSize(e.target.value);
  };

  const handleColorChange = (color) => {
    setQrColor(color.hex);
  };

  const toggleColorPicker = () => {
    setShowColorPicker(!showColorPicker);
  };

  const generateQRCode = () => {
    setQrValue(inputValue);
  };

  const downloadQRCode = () => {
    const canvas = qrRef.current.querySelector('canvas');
    const url = canvas.toDataURL('image/png');
    const a = document.createElement('a');
    
    // Remove http:// or https:// from the beginning
    let filename = inputValue.replace(/^https?:\/\//, '');
    
    // Replace non-alphanumeric characters with underscores and limit length
    filename = filename.replace(/[^a-z0-9]/gi, '_').toLowerCase().slice(0, 20);
    
    // Default to 'qrcode' if filename is empty
    if (!filename) {
      filename = 'qrcode';
    }
    
    a.href = url;
    a.download = `${filename}.png`;
    a.click();
  };

  const getComplementaryColor = (color) => {
    const r = 255 - parseInt(color.slice(1, 3), 16);
    const g = 255 - parseInt(color.slice(3, 5), 16);
    const b = 255 - parseInt(color.slice(5, 7), 16);
    return `rgb(${r}, ${g}, ${b})`;
  };

  const truncateText = (text, maxLength) => {
    return text.length > maxLength ? text.slice(0, maxLength) + '...' : text;
  };

  return (
    <div className="App">
      <h1>QR Code Generator</h1>
      <p className="expl-message">If you think you know what this does, you got it!</p>
      <label>
        Text to encode:
        <input
          type="text"
          value={inputValue}
          onChange={handleInputChange}
          placeholder="Enter text to encode (usually a URL)"
        />
      </label>
      <label>
        Size:
        <input
          type="number"
          value={qrSize}
          onChange={handleSizeChange}
          placeholder="Size of the QR Code"
          min="64"
          max="512"
        />
      </label>
      <label>
        Colour:
        <div className="color-picker-container">
          <button onClick={toggleColorPicker}>
            {showColorPicker ? 'Close Color Picker' : 'Choose Color'}
          </button>
          <div
            className="color-display"
            style={{ backgroundColor: qrColor }}
          />
        </div>
        {showColorPicker && (
          <SketchPicker
            color={qrColor}
            onChangeComplete={handleColorChange}
          />
        )}
      </label>
      <div className="button-group">
        <button onClick={generateQRCode}>Create QR Code</button>
        {qrValue && <button onClick={downloadQRCode}>Download QR Code</button>}
      </div>
      {qrValue && (
        <div className="qr-container" ref={qrRef}>
          <p className="encoded-text" style={{ fontSize: `${Math.max(8, qrSize / 12)}px`, top: '-40px' }}>
            {truncateText(qrValue, 20)}
          </p>
          
          <QRCodeCanvas
            value={qrValue}
            size={parseInt(qrSize, 10)}
            fgColor={qrColor}
          />
          <div
            className="qr-overlay"
            style={{ border: `2px solid ${qrColor}` }}
          >
            BMI
          </div>
          <p className="qr-bottom-text" style={{ fontSize: `${Math.max(10, qrSize / 14)}px`, bottom: `${-qrSize / 8}px` }}>
            By qrcode.buckmaster.ca
          </p>
        </div>
      )}
      <div className="disclaimer">
        <p>This service is totally free; the QR code has no expiry. We are The Buckmaster Institute, Inc., developing web apps at <a href="https://buckmaster.ca" target="_blank" rel="noopener noreferrer">buckmaster.ca</a>.</p>
        <p>Legal Disclaimer: The Buckmaster Institute, Inc. is not responsible for any misuse of the QR codes generated by this service. Use at your own risk.</p>
      </div>
    </div>
  );
}

export default App;
